apiVersion: v1
kind: ConfigMap
metadata:
  name: ironpage-config
  namespace: ironpage
  labels:
    app.kubernetes.io/name: ironpage-vault
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: ironpage
  DB_USER: ironpage
  STORAGE_DIR: /var/lib/ironpage/storage
  BACKUP_DIR: /var/lib/ironpage/backups
  MIGRATIONS_DIR: /opt/ironpage/migrations
  PUBLIC_DIR: /opt/ironpage/public
  HTTP_ADDR: :8080
