apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ironpage-data
  namespace: ironpage
  labels:
    app.kubernetes.io/name: ironpage-vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
