apiVersion: v1
kind: Service
metadata:
  name: ironpage-vault
  namespace: ironpage
  labels:
    app.kubernetes.io/name: ironpage-vault
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ironpage-vault
  ports:
    - name: http
      port: 8080
      targetPort: http
